[project]
name = "stable-diffusion-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "abdulvajid1", email = "vajidca444@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
stable-diffusion-from-scratch = "stable_diffusion_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
